
ServerEvents.recipes(event => {
event.remove({type:'minecraft:smelting', output:'#forge:ingots'})
event.remove({type:'minecraft:blasting', output:'#forge:ingots'})
event.remove({output:'minecraft:blast_furnace'})
event.remove({output:'create:electron_tube'})
event.remove({output:'create:mechanical_press'})
event.remove({output:'create:deployer'})
event.remove({output:'create:mechanical_mixer'})
event.remove({output:'create:empty_blaze_burner'})
event.remove({output:'thermal:rf_coil'})
event.remove({output:'thermal:machine_frame'})
event.remove({output:'thermal:redstone_servo'})
event.remove({output:'create:steam_engine'})
event.remove({output:'createaddition:alternator'})
event.remove({output:'immersiveengineering:coke_brick'})
event.remove({output:'thermal:obsidian_glass'})
event.remove({output:'create:brass_casing'})
event.remove({id: 'thermal:machines/smelter/smelter_alloy_steel'})
event.remove({input:'immersiveengineering:hammer', output:'#forge:dusts'})
event.remove({input:'create:crushed_silver_ore', output: 'thermal:silver_nugget'})
event.remove({input:'create:crushed_tin_ore', output: 'thermal:tin_nugget'})
event.remove({id: 'immersiveengineering:crafting/stick_iron'})
event.remove({id: 'immersiveengineering:crafting/stick_steel'})
event.remove({id: 'immersiveengineering:crafting/stick_aluminum'})
})